version: "2"
services:
  breadquest_server:
    build: breadquest
    restart: on-failure
    volumes:
      - ./breadquest/breadquest:/etc/breadquest/
    ports:
      - "2626:2626"
  breadquest_rl:
    build: rl
    restart: on-failure
    volumes:
      - ./rl:/usr/src/app/

